In [11]:
import numpy as np

In [12]:
# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[25, 2, 1], [5, 26, 2] ])
X

array([[25,  2,  1],
       [ 5, 26,  2]])

In [13]:
# tampilkan ukuran dari matrix X
X.shape

(2, 3)

In [14]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[0]

array([25,  2,  1])

In [15]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X[1]

array([ 5, 26,  2])

In [25]:
import torch

In [26]:
# ulangi soal nomor 1 menggunakan pytorch
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [20]:
import tensorflow as tf

In [27]:
# ulangi soal nomor 1 menggunakan tensorflow
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>