In [1]:
import numpy as np

In [2]:
# buat vector x dengan ukuran 3x1
x = np.array([20, 3, 9])
x

array([20,  3,  9])

In [3]:
# hitung nilai L2 norm dari vector x
(20**2 + 3**2 + 9**2)**(1/2)

22.135943621178654

In [4]:
# buat vector v dengan elemen (3,4)
v = np.array([ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print (v)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
# hitung nilai L2 norm dari vektor v
norm1 = (v[0,0]**2 + v[0,1]**2 + v[0,2]**2 + v[0,3]**2)**(1/2)
norm2 = (v[1,0]**2 + v[1,1]**2 + v[1,2]**2 + v[1,3]**2)**(1/2)
norm3 = (v[2,0]**2 + v[2,1]**2 + v[2,2]**2 + v[2,3]**2)**(1/2)

print("Norm Baris 1:", norm1)
print("Norm Baris 2:", norm2)
print("Norm Baris 3:", norm3)

Norm Baris 1: 5.477225575051661
Norm Baris 2: 13.19090595827292
Norm Baris 3: 21.118712081942874


In [6]:
# tampilkan unit vector dari vector v
unit_vector = v
print(unit_vector)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
# hitung panjang unit vector dari vector v
norm = np.linalg.norm(v)
print(np.linalg.norm(v))

25.495097567963924
