In [1]:
import numpy as np

In [2]:
# buat vector x dengan ukuran 3x1
x = np.array([20, 3, 9])
x

array([20,  3,  9])

In [3]:
# hitung panjang vector x
len(x)

3

In [6]:
# tampilkan ukuran vector x
x.shape

(3,)

In [7]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [8]:
# akses elemen pertama dari vector x
x[0]

np.int64(20)

In [9]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.int64

In [37]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x = np.array([[20, 3, 9]])
x_t

array([[20],
       [ 3],
       [ 9]])

In [12]:
# tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [39]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[20, 3, 9]])
y_transpose

array([[20],
       [ 3],
       [ 9]])

In [14]:
# tampilkan ukuran dari vector x_t
y.shape

(1, 3)

In [15]:
import torch
import tensorflow as tf

In [16]:
# lakukan soal nomor 2 menggunakan pytorch
x_pt = torch.tensor([20, 3, 9])
x_pt

tensor([20,  3,  9])

In [17]:
# lakukan soal nomor 2 menggunakan tensorflow
x_tf = tf.Variable([20, 3, 9])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([20,  3,  9], dtype=int32)>